# @package task
defaults:
  - nlp/default
  - override /backbone@_group_: nlp/seq2seq # Swap to a default seq2seq compatible backbone
  - override /dataset@_group_: nlp/summarization/default
_target_: lightning_transformers.task.nlp.summarization.SummarizationTransformer
downstream_model_type: transformers.AutoModelForSeq2SeqLM
cfg:
  use_stemmer: True
  val_target_max_length: 142
  num_beams: null
  compute_generate_metrics: True
