from lightning_transformers.task.huggingface.multiple_choice.core.data import LitMultipleChoiceTransformerDataModule
from lightning_transformers.task.huggingface.multiple_choice.core.model import LitAutoModelMultipleChoiceTransformer
from lightning_transformers.task.huggingface.multiple_choice.datasets.swag import \
    LitSwagMultipleChoiceTransformerDataModule
