from lightning_transformers.task.huggingface.multiple_choice.core.model import MultipleChoiceTransformer
from lightning_transformers.task.huggingface.multiple_choice.core.data import MultipleChoiceTransformerDataModule
from lightning_transformers.task.huggingface.multiple_choice.datasets.swag import \
    SwagMultipleChoiceTransformerDataModule
